import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text()


class PromptContractTests(unittest.TestCase):
    def test_master_defines_backlog_mode_and_linked_plan_flow(self) -> None:
        master = read(".claude/agents/master.md")
        backlog_updater = read(".claude/agents/backlog-updater.md")
        idea_executor = read(".claude/agents/idea-executor.md")

        self.assertIn("Backlog mode rules:", master)
        self.assertIn("Private backlog", master)
        self.assertIn("Public backlog", master)
        self.assertIn("backlog + linked plan", master)
        self.assertIn("Before I save this backlog item:", master)
        self.assertIn("Approve saving both?", master)
        self.assertIn("Do not let a backlog row become the plan", master)
        self.assertIn("Minimum linked-plan structure:", backlog_updater)
        self.assertIn("## Artifact Visibility", backlog_updater)
        self.assertIn("Linked-plan quality bar:", idea_executor)
        self.assertIn("explain why the chosen visibility is local or tracked", idea_executor)

    def test_local_activity_log_is_optional_and_local_only(self) -> None:
        master = read(".claude/agents/master.md")
        updater = read(".claude/agents/workspace-updater.md")
        setup = read("scripts/setup.sh")
        readme = read("README.md")
        local_context = read("docs/LOCAL_CONTEXT.md")
        durable_memory = read("docs/DURABLE_MEMORY.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        gitignore = read(".gitignore")

        self.assertIn("Local activity log rule:", master)
        self.assertIn(".claude/local-context/ACTIVITY.md", master)
        self.assertIn("Optional local-only trace", setup)
        self.assertIn("Special Case: Local Activity Log", updater)
        self.assertIn(".claude/local-context/ACTIVITY.md", readme)
        self.assertIn("ACTIVITY.md` is the best fit", local_context)
        self.assertIn("Activity log", durable_memory)
        self.assertIn(".claude/local-context/ACTIVITY.md", system_reference)
        self.assertIn(".claude/local-context/", gitignore)

    def test_master_defines_lightweight_and_full_reporting(self) -> None:
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")

        self.assertIn("## Reporting Levels", master)
        self.assertIn("### 1. Lightweight Report", master)
        self.assertIn("### 2. Full Execution Report", master)
        self.assertIn("## Team Activation", master)
        self.assertIn("No delegation was needed because", master)
        self.assertIn("For all tasks, `@master` should at least report:", readme)
        self.assertIn("lightweight visible report even when no delegation was needed", claude)
        self.assertIn("lightweight visible report even when no delegation was needed", agents)

    def test_command_layer_is_tracked_and_visible(self) -> None:
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        for path in [
            ".claude/commands/bootstrap-repo.md",
            ".claude/commands/customize-repo.md",
            ".claude/commands/save-backlog.md",
            ".claude/commands/plan-idea.md",
            ".claude/commands/write-adr.md",
            ".claude/commands/release-check.md",
            ".claude/commands/sync-docs.md",
            ".claude/commands/triage-input.md",
            ".claude/commands/context-audit.md",
            ".claude/commands/review-reference.md",
        ]:
            self.assertTrue((ROOT / path).exists(), path)

        self.assertIn("## Command Layer", master)
        self.assertIn("/bootstrap-repo", master)
        self.assertIn("/customize-repo", master)
        self.assertIn("/review-reference", master)
        self.assertIn("Workflow Commands", readme)
        self.assertIn("Inspect command layer", claude)
        self.assertIn("Inspect command layer", agents)
        self.assertIn(".claude/commands/", architecture)
        self.assertIn("Current command set:", system_reference)

    def test_research_discovery_workflow_is_tracked_and_visible(self) -> None:
        master = read(".claude/agents/master.md")
        researcher = read(".claude/agents/researcher.md")
        team = read(".claude/teams/research-discovery-team.md")
        command = read(".claude/commands/review-reference.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        local_context = read("docs/LOCAL_CONTEXT.md")
        durable_memory = read("docs/DURABLE_MEMORY.md")
        teams_doc = read("docs/TEAMS.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        setup = read("scripts/setup.sh")

        self.assertIn("Research & Discovery Team", master)
        self.assertIn("/review-reference", master)
        self.assertIn("External repo/tool/image/reference fit review", master)
        self.assertIn("## Special Case: Reference And Repo-Fit Reviews", researcher)
        self.assertIn("Research & Discovery Team", team)
        self.assertIn("reference-review workflow", command)
        self.assertIn("docs/RESEARCH_AND_DISCOVERY.md", readme)
        self.assertIn("docs/RESEARCH_AND_DISCOVERY.md", claude)
        self.assertIn("docs/RESEARCH_AND_DISCOVERY.md", agents)
        self.assertIn("docs/RESEARCH_AND_DISCOVERY.md", architecture)
        self.assertIn(".claude/local-context/research/", readme)
        self.assertIn(".claude/local-context/research/", claude)
        self.assertIn(".claude/local-context/research/", agents)
        self.assertIn(".claude/local-context/research/", local_context)
        self.assertIn("Research notes", durable_memory)
        self.assertIn("Research & Discovery Team", teams_doc)
        self.assertIn("Research & Discovery Team", system_reference)
        self.assertIn("/review-reference", system_reference)
        self.assertIn(".claude/local-context/research/README.md", setup)

    def test_master_defines_bootstrap_flow(self) -> None:
        master = read(".claude/agents/master.md")

        self.assertIn("## New Repo Bootstrap", master)
        self.assertIn("Do not trigger bootstrap when:", master)
        self.assertIn("Treat bootstrap as needed when", master)
        self.assertIn("## Repo Customization Mode", master)
        self.assertIn("Listen → Summarize → Deepen", master)
        self.assertIn("### Guided Initialization Mode", master)
        self.assertIn("ask in small rounds, not one giant questionnaire", master)
        self.assertIn("offer likely categories or candidate answers", master)
        self.assertIn("### Pack-Aware Guidance", master)
        self.assertIn("Bootstrap question areas:", master)
        self.assertIn("make a reasonable temporary assumption and label it clearly", master)
        self.assertIn("Before I proceed: this repo still looks under-configured", master)

    def test_bootstrap_and_customization_docs_are_aligned(self) -> None:
        master = read(".claude/agents/master.md")
        bootstrap = read("docs/BOOTSTRAP.md")
        customization = read("docs/PROJECT_CUSTOMIZATION.md")
        readme = read("README.md")
        architecture = read("docs/ARCHITECTURE.md")

        self.assertIn("/customize-repo", readme)
        self.assertIn("Bootstrap Versus Customization", bootstrap)
        self.assertIn("Listen → Summarize → Deepen", bootstrap)
        self.assertIn("core kit layer", customization)
        self.assertIn("repo-specific overlay", customization)
        self.assertIn("/customize-repo", customization)
        self.assertIn("repo-specific overlay", architecture)
        self.assertIn("## Repo Customization Mode", master)

    def test_workspace_updater_understands_bootstrap_follow_up(self) -> None:
        updater = read(".claude/agents/workspace-updater.md")
        master = read(".claude/agents/master.md")
        sync_docs = read(".claude/commands/sync-docs.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        docs_governance = read("docs/DOCUMENTATION_GOVERNANCE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("## Special Case: New Repo Bootstrap", updater)
        self.assertIn("bootstrap flow for a repo outside `claude-team-kit`", updater)
        self.assertIn("call out any still-temporary assumptions clearly", updater)
        self.assertIn("If the master brief says guided initialization was used:", updater)
        self.assertIn("## Doc-Impact Outcomes", updater)
        self.assertIn("No Doc Impact", updater)
        self.assertIn("Targeted Sync Required", updater)
        self.assertIn("Deferred Doc Drift", updater)
        self.assertIn("final doc-impact gate", master)
        self.assertIn("Before commit, push, PR packaging, or release-heavy work:", master)
        self.assertIn("doc-impact gate", sync_docs)
        self.assertIn("adaptive doc-impact gate", readme)
        self.assertIn("final doc-impact gate", claude)
        self.assertIn("final doc-impact gate", agents)
        self.assertIn("doc-impact gate", architecture)
        self.assertIn("adaptive doc-impact gate", docs_governance)
        self.assertIn("doc-impact gate", system_reference)

    def test_private_local_context_rules_are_aligned(self) -> None:
        master = read(".claude/agents/master.md")
        guard = read(".claude/agents/github-safety-guard.md")
        updater = read(".claude/agents/workspace-updater.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        local_context = read("docs/LOCAL_CONTEXT.md")
        gitignore = read(".gitignore")

        self.assertIn("## Private Local Context", master)
        self.assertIn(".claude/local-context/", master)
        self.assertIn("never copy private local-context details into tracked files automatically", master)
        self.assertIn(".claude/local-context/", guard)
        self.assertIn("## Special Case: Private Local Context Boundary", updater)
        self.assertIn("## Private Local Context", readme)
        self.assertIn("private local context layer", claude)
        self.assertIn("private local context layer", agents)
        self.assertIn(".claude/local-context/", local_context)
        self.assertIn(".claude/local-context/", gitignore)

    def test_durable_memory_architecture_is_tracked_and_visible(self) -> None:
        memory_doc = read("docs/DURABLE_MEMORY.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        local_context = read("docs/LOCAL_CONTEXT.md")
        customization = read("docs/PROJECT_CUSTOMIZATION.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Durable Memory", memory_doc)
        self.assertIn("## Memory Layers", memory_doc)
        self.assertIn("## Retrieval Model", memory_doc)
        self.assertIn("## Tracked Versus Local", memory_doc)
        self.assertIn("## How We Actually Achieve Durability", memory_doc)
        self.assertIn("## Memory Flow", memory_doc)
        self.assertIn("```mermaid", memory_doc)
        self.assertIn("## Example Use", memory_doc)
        self.assertIn("docs/DURABLE_MEMORY.md", readme)
        self.assertIn("docs/DURABLE_MEMORY.md", claude)
        self.assertIn("docs/DURABLE_MEMORY.md", agents)
        self.assertIn("docs/DURABLE_MEMORY.md", architecture)
        self.assertIn("docs/DURABLE_MEMORY.md", local_context)
        self.assertIn("memory split", customization)
        self.assertIn("Durable Memory Model", system_reference)

    def test_graph_repo_intelligence_is_tracked_and_visible(self) -> None:
        graph_doc = read("docs/GRAPH_INTELLIGENCE.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        customization = read("docs/PROJECT_CUSTOMIZATION.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Graph And Repo Intelligence", graph_doc)
        self.assertIn("## Why It Must Stay Optional", graph_doc)
        self.assertIn("## When This Layer Is Worth It", graph_doc)
        self.assertIn("## Relationship Layer Versus Code-Intelligence Layer", graph_doc)
        self.assertIn("## Suggested Rollout", graph_doc)
        self.assertIn("## Relationship View", graph_doc)
        self.assertIn("```mermaid", graph_doc)
        self.assertIn("## Example Questions", graph_doc)
        self.assertIn("graph/repo intelligence = artifact relationships", readme)
        self.assertIn("docs/GRAPH_INTELLIGENCE.md", readme)
        self.assertIn("docs/GRAPH_INTELLIGENCE.md", claude)
        self.assertIn("docs/GRAPH_INTELLIGENCE.md", agents)
        self.assertIn("docs/GRAPH_INTELLIGENCE.md", architecture)
        self.assertIn("graph/repo-intelligence layer", customization)
        self.assertIn("Graph / Repo Intelligence", system_reference)

    def test_app_surface_and_mcp_boundary_is_tracked_and_visible(self) -> None:
        app_surface = read("docs/APP_SURFACE_AND_MCP.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        customization = read("docs/PROJECT_CUSTOMIZATION.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        local_context = read("docs/LOCAL_CONTEXT.md")

        self.assertIn("# App Surface And MCP-Connected Systems", app_surface)
        self.assertIn("## Repo-Native Vs App-Native Boundary", app_surface)
        self.assertIn("## First Candidate App Flows", app_surface)
        self.assertIn("## First Candidate MCP-Connected Systems", app_surface)
        self.assertIn("## Privacy And Promotion Boundary", app_surface)
        self.assertIn("docs/APP_SURFACE_AND_MCP.md", readme)
        self.assertIn("docs/APP_SURFACE_AND_MCP.md", claude)
        self.assertIn("docs/APP_SURFACE_AND_MCP.md", agents)
        self.assertIn("docs/APP_SURFACE_AND_MCP.md", architecture)
        self.assertIn("docs/APP_SURFACE_AND_MCP.md", customization)
        self.assertIn("App Surface And MCP Systems", system_reference)
        self.assertIn("future app surface", local_context)

    def test_artifacts_companion_layer_is_tracked_and_visible(self) -> None:
        artifacts = read("docs/ARTIFACTS.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        customization = read("docs/PROJECT_CUSTOMIZATION.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Artifacts Companion Layer", artifacts)
        self.assertIn("## Core Position", artifacts)
        self.assertIn("## Best First Use Cases", artifacts)
        self.assertIn("## Relationship To The App Surface", artifacts)
        self.assertIn("## Public Vs Local Boundary", artifacts)
        self.assertIn("docs/ARTIFACTS.md", readme)
        self.assertIn("docs/ARTIFACTS.md", claude)
        self.assertIn("docs/ARTIFACTS.md", agents)
        self.assertIn("docs/ARTIFACTS.md", customization)
        self.assertIn("Artifacts Companion Layer", system_reference)

    def test_agent_sdk_user_input_compatibility_is_tracked_and_visible(self) -> None:
        sdk = read("docs/AGENT_SDK_USER_INPUT.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        app_surface = read("docs/APP_SURFACE_AND_MCP.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Agent SDK User Input Compatibility", sdk)
        self.assertIn("## What This Actually Refers To", sdk)
        self.assertIn("## Best Future Use Cases", sdk)
        self.assertIn("## What The Core Repo Should Do Today", sdk)
        self.assertIn("## Relationship To The App Surface", sdk)
        self.assertIn("docs/AGENT_SDK_USER_INPUT.md", readme)
        self.assertIn("docs/AGENT_SDK_USER_INPUT.md", claude)
        self.assertIn("docs/AGENT_SDK_USER_INPUT.md", agents)
        self.assertIn("structured SDK-backed user-input handling", app_surface)
        self.assertIn("Agent SDK User Input", system_reference)

    def test_cross_tool_portability_is_tracked_and_visible(self) -> None:
        portability = read("docs/CROSS_TOOL_PORTABILITY.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        customization = read("docs/PROJECT_CUSTOMIZATION.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Cross-Tool Portability", portability)
        self.assertIn("## Portability Tiers", portability)
        self.assertIn("## What Maps Cleanly", portability)
        self.assertIn("## Repo Customization Versus Tool Adaptation", portability)
        self.assertIn("## When A Helper Script Is Justified", portability)
        self.assertIn("docs/CROSS_TOOL_PORTABILITY.md", readme)
        self.assertIn("docs/CROSS_TOOL_PORTABILITY.md", claude)
        self.assertIn("docs/CROSS_TOOL_PORTABILITY.md", agents)
        self.assertIn("docs/CROSS_TOOL_PORTABILITY.md", architecture)
        self.assertIn("docs/CROSS_TOOL_PORTABILITY.md", customization)
        self.assertIn("Cross-Tool Portability", system_reference)

    def test_portability_and_intelligence_overview_is_tracked_and_visible(self) -> None:
        overview = read("docs/PORTABILITY_AND_INTELLIGENCE_OVERVIEW.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Portability And Intelligence Overview", overview)
        self.assertIn("## 1. Canonical Surface Cleanup", overview)
        self.assertIn("## 2. Cross-Tool Portability", overview)
        self.assertIn("## 3. Graph / Repo Intelligence Boundary", overview)
        self.assertIn("```mermaid", overview)
        self.assertIn("docs/PORTABILITY_AND_INTELLIGENCE_OVERVIEW.md", readme)
        self.assertIn("docs/PORTABILITY_AND_INTELLIGENCE_OVERVIEW.md", claude)
        self.assertIn("docs/PORTABILITY_AND_INTELLIGENCE_OVERVIEW.md", agents)
        self.assertIn("docs/PORTABILITY_AND_INTELLIGENCE_OVERVIEW.md", system_reference)

    def test_code_intelligence_integration_is_tracked_and_visible(self) -> None:
        code_intel = read("docs/CODE_INTELLIGENCE_INTEGRATION.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Code-Intelligence Integration", code_intel)
        self.assertIn("## Core Position", code_intel)
        self.assertIn("## Boundary Model", code_intel)
        self.assertIn("## Decision Table", code_intel)
        self.assertIn("## When This Layer Is Worth It", code_intel)
        self.assertIn("docs/CODE_INTELLIGENCE_INTEGRATION.md", readme)
        self.assertIn("docs/CODE_INTELLIGENCE_INTEGRATION.md", claude)
        self.assertIn("docs/CODE_INTELLIGENCE_INTEGRATION.md", agents)
        self.assertIn("docs/CODE_INTELLIGENCE_INTEGRATION.md", architecture)
        self.assertIn("Code-Intelligence Integration", system_reference)

    def test_optional_dependencies_and_adapters_are_tracked_and_visible(self) -> None:
        deps = read("docs/OPTIONAL_DEPENDENCIES_AND_ADAPTERS.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        master = read(".claude/agents/master.md")

        self.assertIn("# Optional Dependencies And Adapters", deps)
        self.assertIn("## Classification Model", deps)
        self.assertIn("## Admission Criteria For Any New External Dependency", deps)
        self.assertIn("## Current Classification Of Reviewed Repos", deps)
        self.assertIn("docs/OPTIONAL_DEPENDENCIES_AND_ADAPTERS.md", readme)
        self.assertIn("docs/OPTIONAL_DEPENDENCIES_AND_ADAPTERS.md", claude)
        self.assertIn("docs/OPTIONAL_DEPENDENCIES_AND_ADAPTERS.md", agents)
        self.assertIn("Optional Dependencies And Adapters", system_reference)
        self.assertIn("optional adapters by default", master)

    def test_code_review_graph_adapter_example_is_tracked_and_visible(self) -> None:
        adapter = read("docs/CODE_REVIEW_GRAPH_ADAPTER_EXAMPLE.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        code_intel = read("docs/CODE_INTELLIGENCE_INTEGRATION.md")

        self.assertIn("# Code-Review-Graph Adapter Example", adapter)
        self.assertIn("## Why This Is The First Example", adapter)
        self.assertIn("## What Stays Outside The Shared Core", adapter)
        self.assertIn("## Example Optional Workflow", adapter)
        self.assertIn("```mermaid", adapter)
        self.assertIn("docs/CODE_REVIEW_GRAPH_ADAPTER_EXAMPLE.md", readme)
        self.assertIn("docs/CODE_REVIEW_GRAPH_ADAPTER_EXAMPLE.md", claude)
        self.assertIn("docs/CODE_REVIEW_GRAPH_ADAPTER_EXAMPLE.md", agents)
        self.assertIn("docs/CODE_REVIEW_GRAPH_ADAPTER_EXAMPLE.md", architecture)
        self.assertIn("Code-Review-Graph Adapter Example", system_reference)
        self.assertIn("docs/CODE_REVIEW_GRAPH_ADAPTER_EXAMPLE.md", code_intel)

    def test_external_skill_repos_are_tracked_and_visible(self) -> None:
        skills = read("docs/EXTERNAL_SKILL_REPOS.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# External Skill Repos", skills)
        self.assertIn("## What Belongs In The Shared Core", skills)
        self.assertIn("## What Belongs In An External Skill Repo", skills)
        self.assertIn("## Installation And Discovery Stance", skills)
        self.assertIn("docs/EXTERNAL_SKILL_REPOS.md", readme)
        self.assertIn("docs/EXTERNAL_SKILL_REPOS.md", claude)
        self.assertIn("docs/EXTERNAL_SKILL_REPOS.md", agents)
        self.assertIn("External Skill Repos", system_reference)

    def test_annotation_aware_context_protocol_is_tracked_and_visible(self) -> None:
        protocol = read("docs/ANNOTATION_AWARE_CONTEXT_PROTOCOL.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Annotation-Aware Context Protocol", protocol)
        self.assertIn("## Core Position", protocol)
        self.assertIn("## Main Risks", protocol)
        self.assertIn("## Adoption Threshold", protocol)
        self.assertIn("docs/ANNOTATION_AWARE_CONTEXT_PROTOCOL.md", readme)
        self.assertIn("docs/ANNOTATION_AWARE_CONTEXT_PROTOCOL.md", claude)
        self.assertIn("docs/ANNOTATION_AWARE_CONTEXT_PROTOCOL.md", agents)
        self.assertIn("docs/ANNOTATION_AWARE_CONTEXT_PROTOCOL.md", architecture)
        self.assertIn("Annotation-Aware Context Protocol", system_reference)

    def test_project_dna_and_state_is_tracked_and_visible(self) -> None:
        dna = read("docs/PROJECT_DNA_AND_STATE.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        master = read(".claude/agents/master.md")
        updater = read(".claude/agents/workspace-updater.md")
        durable_memory = read("docs/DURABLE_MEMORY.md")
        local_context = read("docs/LOCAL_CONTEXT.md")

        self.assertIn("# Project DNA And State", dna)
        self.assertIn("## What Project DNA Is", dna)
        self.assertIn("## What It Is Not", dna)
        self.assertIn("## Relationship To Other Artifacts", dna)
        self.assertIn("## How `@master` Should Recommend It", dna)
        self.assertIn("## How `@workspace-updater` Should Treat It", dna)
        self.assertIn("```mermaid", dna)
        self.assertIn("docs/PROJECT_DNA_AND_STATE.md", readme)
        self.assertIn("docs/PROJECT_DNA_AND_STATE.md", claude)
        self.assertIn("docs/PROJECT_DNA_AND_STATE.md", agents)
        self.assertIn("docs/PROJECT_DNA_AND_STATE.md", architecture)
        self.assertIn("Project DNA And State", system_reference)
        self.assertIn("you may recommend an optional project-DNA artifact", master)
        self.assertIn("docs/PROJECT_DNA.md", updater)
        self.assertIn(".claude/local-context/project-dna.md", updater)
        self.assertIn("docs/PROJECT_DNA_AND_STATE.md", durable_memory)
        self.assertIn("docs/PROJECT_DNA_AND_STATE.md", local_context)

    def test_worktree_parallel_execution_is_tracked_and_visible(self) -> None:
        worktree = read("docs/WORKTREE_PARALLEL_EXECUTION.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        master = read(".claude/agents/master.md")

        self.assertIn("# Worktree Parallel Execution", worktree)
        self.assertIn("## When Worktrees Are Worth It", worktree)
        self.assertIn("## Relationship To The Git / GitHub Quality Gate", worktree)
        self.assertIn("## Relationship To `@master`", worktree)
        self.assertIn("```mermaid", worktree)
        self.assertIn("docs/WORKTREE_PARALLEL_EXECUTION.md", claude)
        self.assertIn("docs/WORKTREE_PARALLEL_EXECUTION.md", agents)
        self.assertIn("docs/WORKTREE_PARALLEL_EXECUTION.md", architecture)
        self.assertIn("Worktree Parallel Execution", system_reference)
        self.assertIn("you may recommend git worktrees as an optional coordination aid", master)

    def test_playbooks_and_batch_workflows_are_tracked_and_visible(self) -> None:
        playbooks = read("docs/PLAYBOOKS_AND_BATCH_WORKFLOWS.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        master = read(".claude/agents/master.md")

        self.assertIn("# Playbooks And Batch Workflows", playbooks)
        self.assertIn("## What A Playbook Is", playbooks)
        self.assertIn("## What A Batch Workflow Is", playbooks)
        self.assertIn("## How This Differs From Other Artifacts", playbooks)
        self.assertIn("## Relationship To Handoff", playbooks)
        self.assertIn("```mermaid", playbooks)
        self.assertIn("docs/PLAYBOOKS_AND_BATCH_WORKFLOWS.md", readme)
        self.assertIn("docs/PLAYBOOKS_AND_BATCH_WORKFLOWS.md", claude)
        self.assertIn("docs/PLAYBOOKS_AND_BATCH_WORKFLOWS.md", agents)
        self.assertIn("docs/PLAYBOOKS_AND_BATCH_WORKFLOWS.md", architecture)
        self.assertIn("Playbooks And Batch Workflows", system_reference)
        self.assertIn("prefer a playbook doc as the durable workflow contract", master)

    def test_one_pager_is_tracked_and_visible(self) -> None:
        one_pager = read("docs/ONE_PAGER.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        updater = read(".claude/agents/workspace-updater.md")

        self.assertIn("# Claude-Team-Kit One-Pager", one_pager)
        self.assertIn("## What This Repo Is", one_pager)
        self.assertIn("## What It Does", one_pager)
        self.assertIn("## How It Works", one_pager)
        self.assertIn("```mermaid", one_pager)
        self.assertIn("docs/ONE_PAGER.md", readme)
        self.assertIn("docs/ONE_PAGER.md", claude)
        self.assertIn("docs/ONE_PAGER.md", agents)
        self.assertIn("docs/ONE_PAGER.md", architecture)
        self.assertIn("One-Pager", system_reference)
        self.assertIn("Tracked high-signal summary doc:", updater)
        self.assertIn("### docs/ONE_PAGER.md", updater)

    def test_backlog_preference_memory_is_tracked_and_visible(self) -> None:
        master = read(".claude/agents/master.md")
        updater = read(".claude/agents/backlog-updater.md")
        memory = read(".claude/agent-memory/backlog-updater/MEMORY.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")

        self.assertIn(".claude/agent-memory/backlog-updater/MEMORY.md", master)
        self.assertIn("Backlog assignment rules:", master)
        self.assertIn("read `.claude/agent-memory/backlog-updater/MEMORY.md`", updater)
        self.assertIn("default assignment convention", memory)
        self.assertIn("reuse it unless the user overrides it", claude)
        self.assertIn("reuse it unless the user overrides it", agents)
        self.assertIn("reuse it unless the user overrides it", readme)

    def test_handoff_artifact_and_tracked_visibility_warning_are_visible(self) -> None:
        updater = read(".claude/agents/workspace-updater.md")
        settings = read(".claude/settings.json")
        local_context = read("docs/LOCAL_CONTEXT.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        architecture = read("docs/ARCHITECTURE.md")
        docs_governance = read("docs/DOCUMENTATION_GOVERNANCE.md")

        self.assertIn("Handoff Update Needed", updater)
        self.assertIn("## Special Case: Local Handoff Artifact", updater)
        self.assertIn("warn-tracked-artifact.sh", settings)
        self.assertIn(".claude/local-context/HANDOFF.md", local_context)
        self.assertIn(".claude/local-context/HANDOFF.md", readme)
        self.assertIn(".claude/local-context/HANDOFF.md", claude)
        self.assertIn(".claude/local-context/HANDOFF.md", agents)
        self.assertIn(".claude/local-context/HANDOFF.md", system_reference)
        self.assertIn("tracked-artifact warning shell hooks", architecture)
        self.assertIn("warn-tracked-artifact.sh", docs_governance)

    def test_context_efficiency_guidance_is_aligned(self) -> None:
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        context = read("docs/CONTEXT_EFFICIENCY.md")
        rtk = read("docs/RTK_INTEGRATION.md")

        self.assertIn("## Context Efficiency And Scope Discipline", master)
        self.assertIn("read narrow first", master)
        self.assertIn("prefer local CLI tools over equivalent MCP tools", master)
        self.assertIn("## Model Routing Policy", master)
        self.assertIn("## Context Efficiency", readme)
        self.assertIn("explicit model-routing stance", readme)
        self.assertIn("docs/CONTEXT_EFFICIENCY.md", readme)
        self.assertIn("docs/RTK_INTEGRATION.md", readme)
        self.assertIn("docs/CONTEXT_EFFICIENCY.md", claude)
        self.assertIn("docs/RTK_INTEGRATION.md", claude)
        self.assertIn("docs/CONTEXT_EFFICIENCY.md", agents)
        self.assertIn("docs/RTK_INTEGRATION.md", agents)
        self.assertIn("## Read Narrow First", context)
        self.assertIn("## Triage Large Inputs First", context)
        self.assertIn("## Default Large-Input Workflow", context)
        self.assertIn("## MCP And Tool Hygiene", context)
        self.assertIn("## Model Routing", context)
        self.assertIn("## Optional RTK Usage", context)
        self.assertIn("rtk-ai/rtk", rtk)
        self.assertIn("## Why It Stays Optional", rtk)
        self.assertIn("## Installation", rtk)

    def test_large_input_triage_workflow_is_explicit(self) -> None:
        master = read(".claude/agents/master.md")
        command = read(".claude/commands/triage-input.md")
        skill = read(".claude/skills/triage-input/SKILL.md")
        readme = read("README.md")
        workflows = read("docs/AGENT_WORKFLOWS.md")

        self.assertIn("Default large-input workflow:", master)
        self.assertIn("Default handoff preferences after triage:", master)
        self.assertIn('compact "Input Triage Report"', master)
        self.assertIn("classify the input shape and size before reading deeply", command)
        self.assertIn("suggested handoff", command)
        self.assertIn("Step 0: Decide whether full triage is needed", skill)
        self.assertIn("Step 5: Suggest the best owner for the next step", skill)
        self.assertIn("default large-input workflow", readme)
        self.assertIn("Workflow 12 — Large-Input Triage Flow", workflows)

    def test_noisy_task_routing_prefers_specialists(self) -> None:
        master = read(".claude/agents/master.md")
        context = read("docs/CONTEXT_EFFICIENCY.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")

        self.assertIn("Specialist-first routing for noisy tasks:", master)
        self.assertIn("log-heavy or traceback-heavy debugging", master)
        self.assertIn("structured data, analytics evidence", master)
        self.assertIn("## Specialist-First Routing For Noisy Tasks", context)
        self.assertIn("Data Team", context)
        self.assertIn("specialist-first", readme)
        self.assertIn("specialist-first routing", claude)
        self.assertIn("specialist-first routing", agents)

    def test_model_routing_policy_is_visible_and_specific(self) -> None:
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        context = read("docs/CONTEXT_EFFICIENCY.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        backlog_curator = read(".claude/agents/backlog-curator.md")
        changelog_writer = read(".claude/agents/changelog-writer.md")
        feedback_synthesizer = read(".claude/agents/feedback-synthesizer.md")
        delivery_monitor = read(".claude/agents/delivery-monitor.md")

        self.assertIn("`Haiku`", master)
        self.assertIn("`Sonnet`", master)
        self.assertIn("`Opus`", master)
        self.assertIn("Low-risk cheaper-by-default agents now include", readme)
        self.assertIn("route models intentionally", claude)
        self.assertIn("route models intentionally", agents)
        self.assertIn("Prefer `Haiku` for", context)
        self.assertIn("Prefer `Sonnet` for", context)
        self.assertIn("Prefer `Opus` for", context)
        self.assertIn("## Model Defaults", system_reference)
        self.assertIn("model: haiku", backlog_curator)
        self.assertIn("model: haiku", changelog_writer)
        self.assertIn("model: haiku", feedback_synthesizer)
        self.assertIn("model: haiku", delivery_monitor)

    def test_governance_rules_are_tracked_and_linked(self) -> None:
        documentation = read(".claude/rules/documentation-governance.md")
        cleanup_rule = read(".claude/rules/repo-cleanup.md")
        artifact = read(".claude/rules/artifact-governance.md")
        context_rule = read(".claude/rules/context-efficiency.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        docs_governance = read("docs/DOCUMENTATION_GOVERNANCE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("Keep `README.md`, `CLAUDE.md`, and `AGENTS.md` aligned", documentation)
        self.assertIn("After this kit is copied into a real repo", cleanup_rule)
        self.assertIn("Use `BACKLOG.md` for private local deferred work", artifact)
        self.assertIn("Read narrow first", context_rule)
        self.assertIn("docs/VISION.example.md", readme)
        self.assertIn("docs/VISION.example.md", claude)
        self.assertIn("docs/VISION.example.md", agents)
        self.assertIn("docs/ROADMAP.example.md", readme)
        self.assertIn("docs/ROADMAP.example.md", claude)
        self.assertIn("docs/ROADMAP.example.md", agents)
        self.assertIn("docs/SELF_UPGRADE.md", readme)
        self.assertIn("docs/SELF_UPGRADE.md", claude)
        self.assertIn("docs/SELF_UPGRADE.md", agents)
        self.assertIn("docs/STARTER_PACKS.md", readme)
        self.assertIn("docs/STARTER_PACKS.md", claude)
        self.assertIn("docs/STARTER_PACKS.md", agents)
        self.assertIn("docs/SOLUTION_PACKS.md", readme)
        self.assertIn("docs/SOLUTION_PACKS.md", claude)
        self.assertIn("docs/SOLUTION_PACKS.md", agents)
        self.assertIn("docs/DESIGN_PACKS.md", readme)
        self.assertIn("docs/DESIGN_PACKS.md", claude)
        self.assertIn("docs/DESIGN_PACKS.md", agents)
        self.assertIn("hot path lean", docs_governance)
        self.assertIn("full feature and connection map", system_reference)
        self.assertIn("@.claude/rules/documentation-governance.md", claude)
        self.assertIn("@.claude/rules/documentation-governance.md", agents)
        self.assertIn("@.claude/rules/repo-cleanup.md", claude)
        self.assertIn("@.claude/rules/repo-cleanup.md", agents)
        self.assertIn("@.claude/rules/artifact-governance.md", claude)
        self.assertIn("@.claude/rules/artifact-governance.md", agents)
        self.assertIn("@.claude/rules/context-efficiency.md", claude)
        self.assertIn("@.claude/rules/context-efficiency.md", agents)
        self.assertIn("documentation alignment", architecture)
        self.assertIn("artifact placement", architecture)

    def test_self_upgrade_guide_is_visible_and_actionable(self) -> None:
        guide = read("docs/SELF_UPGRADE.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        docs_governance = read("docs/DOCUMENTATION_GOVERNANCE.md")

        self.assertIn("## Surface Selection", guide)
        self.assertIn("## Public vs Local Boundary", guide)
        self.assertIn("## Validation Standard", guide)
        self.assertIn("docs/SELF_UPGRADE.md", readme)
        self.assertIn("docs/SELF_UPGRADE.md", claude)
        self.assertIn("docs/SELF_UPGRADE.md", agents)
        self.assertIn("docs/SELF_UPGRADE.md", architecture)
        self.assertIn("docs/SELF_UPGRADE.md", system_reference)
        self.assertIn("docs/SELF_UPGRADE.md", docs_governance)

    def test_starter_packs_are_tracked_and_visible(self) -> None:
        packs = read("docs/STARTER_PACKS.md")
        saas = read("docs/starter-packs/saas-app.md")
        api = read("docs/starter-packs/api-service.md")
        ai_ml = read("docs/starter-packs/ai-ml-product.md")
        studio = read("docs/starter-packs/startup-studio.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        customization = read("docs/PROJECT_CUSTOMIZATION.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("## Available Packs", packs)
        self.assertIn("SaaS App", packs)
        self.assertIn("API Service", packs)
        self.assertIn("AI/ML Product", packs)
        self.assertIn("Startup Studio", packs)
        self.assertIn("## Team Emphasis", saas)
        self.assertIn("## Team Emphasis", api)
        self.assertIn("## Team Emphasis", ai_ml)
        self.assertIn("## Team Emphasis", studio)
        self.assertIn("docs/STARTER_PACKS.md", readme)
        self.assertIn("docs/STARTER_PACKS.md", claude)
        self.assertIn("docs/STARTER_PACKS.md", agents)
        self.assertIn("docs/STARTER_PACKS.md", customization)
        self.assertIn("docs/STARTER_PACKS.md", system_reference)

    def test_solution_packs_are_tracked_and_visible(self) -> None:
        packs = read("docs/SOLUTION_PACKS.md")
        library = read("docs/solution-packs/README.md")
        supabase_pack = read("docs/solution-packs/supabase-foundation.md")
        github_pack = read("docs/solution-packs/github-cicd-foundation.md")
        vercel_pack = read("docs/solution-packs/vercel-foundation.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        customization = read("docs/PROJECT_CUSTOMIZATION.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Solution Packs", packs)
        self.assertIn("## How They Fit", packs)
        self.assertIn("## Starter Packs Vs Solution Packs", packs)
        self.assertIn("## What A Solution Pack Should Contain", packs)
        self.assertIn("## Public Vs Local Boundary", packs)
        self.assertIn("## Recommended First-Wave Packs", packs)
        self.assertIn("Supabase Application Foundation", library)
        self.assertIn("GitHub And CI/CD Foundation", library)
        self.assertIn("Vercel Deployment Foundation", library)
        self.assertIn("# Supabase Application Foundation", supabase_pack)
        self.assertIn("# GitHub And CI/CD Foundation", github_pack)
        self.assertIn("# Vercel Deployment Foundation", vercel_pack)
        self.assertIn("## Expected Repo Surface", supabase_pack)
        self.assertIn("## Quality Gates", supabase_pack)
        self.assertIn("## Branch And PR Guidance", github_pack)
        self.assertIn("## CI/CD Guidance", github_pack)
        self.assertIn("## Preview And Production Workflow", vercel_pack)
        self.assertIn("## Domain And DNS Guidance", vercel_pack)
        self.assertIn("docs/solution-packs/supabase-foundation.md", packs)
        self.assertIn("docs/solution-packs/github-cicd-foundation.md", packs)
        self.assertIn("docs/solution-packs/vercel-foundation.md", packs)
        self.assertIn("docs/solution-packs/supabase-foundation.md", readme)
        self.assertIn("docs/solution-packs/github-cicd-foundation.md", readme)
        self.assertIn("docs/solution-packs/vercel-foundation.md", readme)
        self.assertIn("docs/SOLUTION_PACKS.md", readme)
        self.assertIn("docs/SOLUTION_PACKS.md", claude)
        self.assertIn("docs/SOLUTION_PACKS.md", agents)
        self.assertIn("docs/SOLUTION_PACKS.md", customization)
        self.assertIn("docs/SOLUTION_PACKS.md", system_reference)

    def test_design_packs_are_tracked_and_visible(self) -> None:
        packs = read("docs/DESIGN_PACKS.md")
        library = read("docs/design-packs/README.md")
        clean_saas = read("docs/design-packs/clean-saas.md")
        startup_studio = read("docs/design-packs/startup-studio.md")
        premium_service = read("docs/design-packs/premium-service.md")
        technical_console = read("docs/design-packs/technical-console.md")
        reference = read("docs/DESIGN_REFERENCE.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        customization = read("docs/PROJECT_CUSTOMIZATION.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Design Packs", packs)
        self.assertIn("## How They Fit", packs)
        self.assertIn("## Relationship To `DESIGN.md`", packs)
        self.assertIn("## What A Design Pack Should Contain", packs)
        self.assertIn("## `DESIGN.md` Workflow", packs)
        self.assertIn("## Recommended First Design-Pack Types", packs)
        self.assertIn("Current library:", library)
        self.assertIn("# Clean SaaS Product", clean_saas)
        self.assertIn("## Best Fit", clean_saas)
        self.assertIn("# Startup Studio / Founder Service", startup_studio)
        self.assertIn("## Brand And Interaction Direction", startup_studio)
        self.assertIn("# Premium Service / Advisory", premium_service)
        self.assertIn("## Surface Rules", premium_service)
        self.assertIn("# Technical Console / Dashboard", technical_console)
        self.assertIn("## Design Guardrails", technical_console)
        self.assertIn("Design Team And Design Packs", reference)
        self.assertIn("docs/DESIGN_PACKS.md", readme)
        self.assertIn("docs/design-packs/clean-saas.md", readme)
        self.assertIn("docs/DESIGN_PACKS.md", claude)
        self.assertIn("docs/DESIGN_PACKS.md", agents)
        self.assertIn("docs/DESIGN_PACKS.md", customization)
        self.assertIn("docs/DESIGN_PACKS.md", system_reference)

    def test_doc_drift_hook_is_tracked_and_registered(self) -> None:
        settings = read(".claude/settings.json")
        hook = read(".claude/hooks/warn-doc-drift.sh")
        readme = read("README.md")
        architecture = read("docs/ARCHITECTURE.md")

        self.assertIn("warn-doc-drift.sh", settings)
        self.assertIn("DOC DRIFT CHECK", hook)
        self.assertIn("doc-drift warning", readme)
        self.assertIn("drift-warning shell hooks", architecture)

    def test_new_skills_are_tracked_and_visible(self) -> None:
        context_audit = read(".claude/skills/context-audit/SKILL.md")
        triage_input = read(".claude/skills/triage-input/SKILL.md")
        repo_cleanup = read(".claude/skills/repo-cleanup/SKILL.md")
        readme = read("README.md")
        context = read("docs/CONTEXT_EFFICIENCY.md")

        self.assertIn("Audit the repo's working context", context_audit)
        self.assertIn("Triage this input first", triage_input)
        self.assertIn("Audit a copied repo for generic kit leftovers", repo_cleanup)
        self.assertIn("20 reusable skills", readme)
        self.assertIn("context-audit", readme)
        self.assertIn("triage-input", readme)
        self.assertIn("repo-cleanup", readme)
        self.assertIn("`triage-input` skill", context)
        self.assertIn("`context-audit` skill", context)

    def test_git_github_team_is_defined_and_visible(self) -> None:
        team = read(".claude/teams/git-github-team.md")
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        teams_doc = read("docs/TEAMS.md")

        self.assertIn("# Git / GitHub Team", team)
        self.assertIn("@github-safety-guard", team)
        self.assertIn("Git / GitHub Team", master)
        self.assertIn("git, GitHub, PR, or repository-safety work", master)
        self.assertIn("Git / GitHub Team", readme)
        self.assertIn("Git / GitHub Team", claude)
        self.assertIn("Git / GitHub Team", agents)
        self.assertIn("Git / GitHub Team", teams_doc)
        self.assertIn("lightweight sync-readiness check", master)
        self.assertIn("quick sync check or pull", readme)
        self.assertIn("quick sync check or pull", claude)
        self.assertIn("quick sync check or pull", agents)

    def test_session_budget_estimator_is_tracked_and_visible(self) -> None:
        estimator = read(".claude/agents/session-budget-estimator.md")
        memory = read(".claude/agent-memory/session-budget-estimator/MEMORY.md")
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        backlog_template = read("BACKLOG.example.md")
        public_backlog_template = read("docs/BACKLOG.example.md")
        roadmap_template = read("docs/ROADMAP.example.md")

        self.assertIn("Session Budget Estimator", estimator)
        self.assertIn("Session Mode", estimator)
        self.assertIn("Roadmap Mode", estimator)
        self.assertIn("Hybrid Mode", estimator)
        self.assertIn("estimate-versus-outcome logs in local context", memory)
        self.assertIn("Session budget / reset-limit / model-capacity estimate", master)
        self.assertIn("Estimation mode rules:", master)
        self.assertIn("recommend `Session Mode`", master)
        self.assertIn("@session-budget-estimator", readme)
        self.assertIn("specialized agents", readme)
        self.assertIn("@session-budget-estimator", claude)
        self.assertIn("@session-budget-estimator", agents)
        self.assertIn("@session-budget-estimator", system_reference)
        self.assertIn(".claude/local-context/estimation-log.md", system_reference)
        self.assertIn("@session-budget-estimator", backlog_template)
        self.assertIn("@session-budget-estimator", public_backlog_template)
        self.assertIn("@session-budget-estimator", roadmap_template)

    def test_strategy_reviewer_is_tracked_and_visible(self) -> None:
        reviewer = read(".claude/agents/strategy-reviewer.md")
        memory = read(".claude/agent-memory/strategy-reviewer/MEMORY.md")
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        teams_doc = read("docs/TEAMS.md")
        workflows = read("docs/AGENT_WORKFLOWS.md")
        advisory_team = read(".claude/teams/advisory-review-team.md")

        self.assertIn("Strategy Reviewer", reviewer)
        self.assertIn("Strong fit", reviewer)
        self.assertIn("Moderate fit", reviewer)
        self.assertIn("Weak fit", reviewer)
        self.assertIn("Misaligned", reviewer)
        self.assertIn("strategic fit, roadmap fit, leverage, timing", memory)
        self.assertIn("Strategic fit / roadmap fit / portfolio pushback", master)
        self.assertIn("Automatic strategy-review trigger rules:", master)
        self.assertIn("@strategy-reviewer", readme)
        self.assertIn("specialized agents", readme)
        self.assertIn("@strategy-reviewer", claude)
        self.assertIn("@strategy-reviewer", agents)
        self.assertIn("@strategy-reviewer", system_reference)
        self.assertIn("@strategy-reviewer", teams_doc)
        self.assertIn("@strategy-reviewer", workflows)
        self.assertIn("@strategy-reviewer", advisory_team)

    def test_vision_partner_is_tracked_and_visible(self) -> None:
        partner = read(".claude/agents/vision-partner.md")
        memory = read(".claude/agent-memory/vision-partner/MEMORY.md")
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        teams_doc = read("docs/TEAMS.md")
        workflows = read("docs/AGENT_WORKFLOWS.md")
        advisory_team = read(".claude/teams/advisory-review-team.md")

        self.assertIn("Vision Partner", partner)
        self.assertIn("## Vision Partner Brief", partner)
        self.assertIn("think alongside the user", partner)
        self.assertIn("strong next-move patterns", memory)
        self.assertIn("Collaborative next-move generation / vision-backlog-roadmap connection", master)
        self.assertIn("@vision-partner", readme)
        self.assertIn("53 specialized agents", readme)
        self.assertIn("@vision-partner", claude)
        self.assertIn("@vision-partner", agents)
        self.assertIn("@vision-partner", system_reference)
        self.assertIn("@vision-partner", teams_doc)
        self.assertIn("@vision-partner", workflows)
        self.assertIn("@vision-partner", advisory_team)

    def test_plan_visibility_prompting_is_explicit(self) -> None:
        master = read(".claude/agents/master.md")
        idea_executor = read(".claude/agents/idea-executor.md")
        backlog_updater = read(".claude/agents/backlog-updater.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        workflows = read("docs/AGENT_WORKFLOWS.md")

        self.assertIn("do not treat approval to save a plan as approval to track it publicly", master)
        self.assertIn("approving the plan itself is separate from deciding whether it stays local or becomes part of tracked git history", master)
        self.assertIn("Do not treat \"approve the plan\" and \"approve tracking the plan publicly\" as the same approval", idea_executor)
        self.assertIn("if `@master` has not confirmed local versus tracked visibility, do not create `docs/plans/<slug>.md`", backlog_updater)
        self.assertIn("approving a plan is not the same as approving a tracked public plan", readme)
        self.assertIn("must ask explicitly which visibility the user wants", claude)
        self.assertIn("must ask explicitly which visibility the user wants", agents)
        self.assertIn("Local or tracked", workflows)

    def test_team_aware_reporting_is_visible(self) -> None:
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")

        self.assertIn("Primary Team:", master)
        self.assertIn("which team was primary, if a team was used", readme)
        self.assertIn("must identify the primary team, team lead, and activation reason", claude)
        self.assertIn("must identify the primary team, team lead, and activation reason", agents)

    def test_supabase_team_is_defined_and_visible(self) -> None:
        team = read(".claude/teams/supabase-team.md")
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        teams_doc = read("docs/TEAMS.md")
        workflows = read("docs/AGENT_WORKFLOWS.md")
        customization = read("docs/PROJECT_CUSTOMIZATION.md")
        reference = read("docs/SUPABASE_REFERENCE.md")

        self.assertIn("# Supabase Team", team)
        self.assertIn("@security-auditor", team)
        self.assertIn("Supabase Team", master)
        self.assertIn("Supabase auth, schema, migrations, RLS, storage, or edge-function work", master)
        self.assertIn("Supabase Team", readme)
        self.assertIn("Supabase Team", claude)
        self.assertIn("Supabase Team", agents)
        self.assertIn("Supabase Team", teams_doc)
        self.assertIn("Workflow 10 — Supabase Team Flow", workflows)
        self.assertIn("If The Project Uses Supabase", customization)
        self.assertIn("What Supabase Is", reference)

    def test_data_team_is_defined_and_visible(self) -> None:
        team = read(".claude/teams/data-team.md")
        data_engineer = read(".claude/agents/data-engineer.md")
        analytics_engineer = read(".claude/agents/analytics-engineer.md")
        data_analyst = read(".claude/agents/data-analyst.md")
        experiment_analyst = read(".claude/agents/experiment-analyst.md")
        governance = read(".claude/agents/data-governance-reviewer.md")
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        teams_doc = read("docs/TEAMS.md")
        workflows = read("docs/AGENT_WORKFLOWS.md")
        customization = read("docs/PROJECT_CUSTOMIZATION.md")
        reference = read("docs/DATA_REFERENCE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Data Team", team)
        self.assertIn("@data-governance-reviewer", team)
        self.assertIn("senior data engineer", data_engineer)
        self.assertIn("senior analytics engineer", analytics_engineer)
        self.assertIn("senior data analyst", data_analyst)
        self.assertIn("experimentation analyst", experiment_analyst)
        self.assertIn("data governance reviewer", governance)
        self.assertIn("Data Team", master)
        self.assertIn("data pipelines, warehouse modeling, analytics, experimentation, or data governance work", master)
        self.assertIn("Data Team", readme)
        self.assertIn("Data Team", claude)
        self.assertIn("Data Team", agents)
        self.assertIn("Data Team", teams_doc)
        self.assertIn("Workflow 11 — Data Team Flow", workflows)
        self.assertIn("If The Project Has A Real Data Stack", customization)
        self.assertIn("What The Data Team Is", reference)
        self.assertIn("### Data", system_reference)

    def test_design_team_is_defined_and_visible(self) -> None:
        team = read(".claude/teams/design-team.md")
        product_designer = read(".claude/agents/product-designer.md")
        ui_designer = read(".claude/agents/ui-designer.md")
        brand_designer = read(".claude/agents/brand-designer.md")
        systems_architect = read(".claude/agents/design-systems-architect.md")
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        teams_doc = read("docs/TEAMS.md")
        workflows = read("docs/AGENT_WORKFLOWS.md")
        customization = read("docs/PROJECT_CUSTOMIZATION.md")
        reference = read("docs/DESIGN_REFERENCE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Design Team", team)
        self.assertIn("@design-systems-architect", team)
        self.assertIn("Product Designer", product_designer)
        self.assertIn("UI Designer", ui_designer)
        self.assertIn("Brand Designer", brand_designer)
        self.assertIn("Design Systems Architect", systems_architect)
        self.assertIn("Design Team", master)
        self.assertIn("product UX, UI layout, design-system, brand, or presentation-heavy surface work", master)
        self.assertIn("Design Team", readme)
        self.assertIn("Design Team", claude)
        self.assertIn("Design Team", agents)
        self.assertIn("Design Team", teams_doc)
        self.assertIn("Workflow 13 — Design Team Flow", workflows)
        self.assertIn("If The Project Has Real Design Surfaces", customization)
        self.assertIn("What The Design Team Is", reference)
        self.assertIn("### Design", system_reference)

    def test_executive_team_is_defined_and_visible(self) -> None:
        team = read(".claude/teams/executive-team.md")
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        teams_doc = read("docs/TEAMS.md")
        workflows = read("docs/AGENT_WORKFLOWS.md")
        architecture = read("docs/ARCHITECTURE.md")
        local_context = read("docs/LOCAL_CONTEXT.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Executive Team", team)
        self.assertIn("@strategy-reviewer", team)
        self.assertIn("Executive Team", master)
        self.assertIn("public-kit vs private-product boundary work", master)
        self.assertIn("Executive Team", readme)
        self.assertIn("Executive Team", claude)
        self.assertIn("Executive Team", agents)
        self.assertIn("Executive Team", teams_doc)
        self.assertIn("Workflow 14 — Executive Team Flow", workflows)
        self.assertIn("Private product incubation or proof-of-concept work can live alongside that kit", architecture)
        self.assertIn("private proof-of-concept or core-product incubation notes", local_context)
        self.assertIn(".claude/local-context/proof-of-concept/", system_reference)

    def test_product_discovery_team_is_defined_and_visible(self) -> None:
        team = read(".claude/teams/product-discovery-team.md")
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        teams_doc = read("docs/TEAMS.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Product Discovery Team", team)
        self.assertIn("MVP reduction", team)
        self.assertIn("Product Discovery Team", master)
        self.assertIn("what should not be built yet", master)
        self.assertIn("Product Discovery Team", readme)
        self.assertIn("Product Discovery Team", claude)
        self.assertIn("Product Discovery Team", agents)
        self.assertIn("Product Discovery Team", teams_doc)
        self.assertIn("Product Discovery Team", system_reference)

    def test_product_launch_team_is_defined_and_visible(self) -> None:
        team = read(".claude/teams/product-launch-team.md")
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        teams_doc = read("docs/TEAMS.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("# Product Launch Team", team)
        self.assertIn("launch-ready", team)
        self.assertIn("Product Launch Team", master)
        self.assertIn("cross-functional app/website build-to-launch work", master)
        self.assertIn("Product Launch Team", readme)
        self.assertIn("Product Launch Team", claude)
        self.assertIn("Product Launch Team", agents)
        self.assertIn("Product Launch Team", teams_doc)
        self.assertIn("Product Launch Team", system_reference)

    def test_idea_to_production_guide_is_tracked_and_visible(self) -> None:
        guide = read("docs/IDEA_TO_PRODUCTION.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        updater = read(".claude/agents/workspace-updater.md")

        self.assertIn("# Idea To Production", guide)
        self.assertIn("## The Recommended Journey", guide)
        self.assertIn("Product Discovery Team", guide)
        self.assertIn("Product Launch Team", guide)
        self.assertIn("What Is Not Needed Yet", guide)
        self.assertIn("docs/IDEA_TO_PRODUCTION.md", readme)
        self.assertIn("docs/IDEA_TO_PRODUCTION.md", claude)
        self.assertIn("docs/IDEA_TO_PRODUCTION.md", agents)
        self.assertIn("docs/IDEA_TO_PRODUCTION.md", system_reference)
        self.assertIn("docs/IDEA_TO_PRODUCTION.md", updater)

    def test_github_quality_gate_agents_and_rule_are_visible(self) -> None:
        code_reviewer = read(".claude/agents/code-reviewer.md")
        pr_operator = read(".claude/agents/pr-operator.md")
        prod_ready = read(".claude/agents/production-readiness-reviewer.md")
        quality_gate = read(".claude/rules/github-quality-gate.md")
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        teams_doc = read("docs/TEAMS.md")
        workflows = read("docs/AGENT_WORKFLOWS.md")

        self.assertIn("Production-grade code reviewer", code_reviewer)
        self.assertIn("Pull-request readiness", pr_operator)
        self.assertIn("Final production-readiness gate", prod_ready)
        self.assertIn("Code should not be committed, pushed, or packaged for PR as \"ready\"", quality_gate)

    def test_release_governance_pack_is_visible(self) -> None:
        release_rule = read(".claude/rules/release-governance.md")
        release_doc = read("docs/RELEASE_GOVERNANCE.md")
        release_command = read(".claude/commands/release-check.md")
        git_team = read(".claude/teams/git-github-team.md")
        teams_doc = read("docs/TEAMS.md")
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        workflows = read("docs/AGENT_WORKFLOWS.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("Default Release Governance Sequence", release_rule)
        self.assertIn("READY WITH NOTED RISK", release_rule)
        self.assertIn("This kit also includes a stricter release-governance layer", readme)
        self.assertIn("@.claude/rules/release-governance.md", claude)
        self.assertIn("@.claude/rules/release-governance.md", agents)
        self.assertIn("release-governance report", release_command)
        self.assertIn("release-governance check", git_team)
        self.assertIn("For **any release-heavy path** prefer an explicit release-governance sequence", master)
        self.assertIn("READY WITH NOTED RISK", master)
        self.assertIn("release-heavy paths should end in a visible `READY`, `READY WITH NOTED RISK`, or `NOT READY` summary", workflows)
        self.assertIn("release-governance.md", system_reference)
        self.assertIn("Git / GitHub blocking policy:", master)
        self.assertIn("GitHub Quality Gate", readme)
        self.assertIn("@.claude/rules/github-quality-gate.md", claude)
        self.assertIn("@.claude/rules/github-quality-gate.md", agents)
        self.assertIn("@code-reviewer", teams_doc)
        self.assertIn("@code-reviewer", workflows)

    def test_request_shaping_guidance_is_aligned(self) -> None:
        master = read(".claude/agents/master.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")

        self.assertIn("prefer clear step-by-step guidance over vague advice", master)
        self.assertIn("when a pre-made guide, pack, command, or workflow already fits", master)
        self.assertIn("## How To Ask Well", readme)
        self.assertIn("exact file paths", claude)
        self.assertIn("exact file paths", agents)

    def test_readme_includes_badges_and_hero(self) -> None:
        readme = read("README.md")
        hero = read("docs/assets/claude-team-kit-hero.svg")

        self.assertIn("github/actions/workflow/status/Konstantinos-Sakellariou/claude-team-kit/validate.yml", readme)
        self.assertIn("claude-team-kit hero", readme)
        self.assertIn("<svg", hero)
        self.assertIn("Operational Layers", hero)

    def test_backlog_updater_schema_includes_assignment_and_artifact(self) -> None:
        backlog_updater = read(".claude/agents/backlog-updater.md")

        self.assertIn("Assigned", backlog_updater)
        self.assertIn("Artifact / Plan", backlog_updater)
        self.assertIn("docs/BACKLOG.md", backlog_updater)
        self.assertIn("Do not change the `Status` of an existing backlog item unless the user explicitly asked", backlog_updater)

    def test_idea_executor_distinguishes_backlog_only_vs_backlog_plus_plan(self) -> None:
        idea_executor = read(".claude/agents/idea-executor.md")

        self.assertIn("Backlog Only", idea_executor)
        self.assertIn("Backlog + Plan", idea_executor)
        self.assertIn("Proposed Backlog Target", idea_executor)
        self.assertIn("Proposed Plan Path", idea_executor)

    def test_backlog_templates_share_the_extended_schema(self) -> None:
        private_template = read("BACKLOG.example.md")
        public_template = read("docs/BACKLOG.example.md")

        for content in (private_template, public_template):
            self.assertIn("Assigned", content)
            self.assertIn("Artifact / Plan", content)
            self.assertIn("| ID | Idea | Description |", content)
            self.assertIn("VISION.example.md", content)
            self.assertIn("ROADMAP.example.md", content)

    def test_roadmap_is_tracked_and_linked(self) -> None:
        roadmap = read("docs/ROADMAP.example.md")
        vision = read("docs/VISION.example.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        architecture = read("docs/ARCHITECTURE.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")
        backlog_updater = read(".claude/agents/backlog-updater.md")
        master = read(".claude/agents/master.md")

        self.assertIn("# Roadmap Template", roadmap)
        self.assertIn("## Phased Roadmap", roadmap)
        self.assertIn("## Timeline View", roadmap)
        self.assertIn("# Vision Template", vision)
        self.assertIn("## Suggested Structure", vision)
        self.assertIn("docs/ROADMAP.example.md", readme)
        self.assertIn("docs/ROADMAP.example.md", claude)
        self.assertIn("docs/ROADMAP.example.md", agents)
        self.assertIn("docs/ROADMAP.example.md", architecture)
        self.assertIn("docs/ROADMAP.example.md", system_reference)
        self.assertIn("docs/ROADMAP.example.md", backlog_updater)
        self.assertIn("docs/ROADMAP.example.md", master)

    def test_bootstrap_docs_exist_and_are_aligned(self) -> None:
        bootstrap = read("docs/BOOTSTRAP.md")
        readme = read("README.md")
        claude = read("CLAUDE.md")
        agents = read("AGENTS.md")
        workflows = read("docs/AGENT_WORKFLOWS.md")
        customization = read("docs/PROJECT_CUSTOMIZATION.md")
        system_reference = read("docs/SYSTEM_REFERENCE.md")

        self.assertIn("When `claude-team-kit` is dropped into a repo other than itself", bootstrap)
        self.assertIn("private local context layer", bootstrap)
        self.assertIn("## Guided Initialization", bootstrap)
        self.assertIn("## Company-Building Workflow Mode", bootstrap)
        self.assertIn("### Founder / Company-Building Rounds", bootstrap)
        self.assertIn("## Suggested Rounds", bootstrap)
        self.assertIn("## New Repo Bootstrap", readme)
        self.assertIn("guided initialization style", readme)
        self.assertIn("company-building workflow", readme)
        self.assertIn("docs/BOOTSTRAP.md", readme)
        self.assertIn("Bootstrap should stay flexible:", claude)
        self.assertIn("use guided initialization when the repo is especially underdefined", claude)
        self.assertIn("company-building workflow mode", claude)
        self.assertIn("Bootstrap should stay flexible:", agents)
        self.assertIn("use guided initialization when the repo is especially underdefined", agents)
        self.assertIn("company-building workflow mode", agents)
        self.assertIn("Workflow 15 — Company-Building Workflow", workflows)
        self.assertIn("company-building workflow", customization)
        self.assertIn("company-building workflow model", system_reference)

    def test_adr_guidance_is_aligned_across_docs_prompt_and_skill(self) -> None:
        adr_readme = read("docs/adr/README.md")
        tech_writer = read(".claude/agents/tech-writer.md")

        self.assertIn("docs/adr/001-decision-name.md", adr_readme)
        self.assertIn("docs/adr/001-decision-name.md", tech_writer)

        for required in [
            "Date",
            "Status",
            "Deciders",
            "Context",
            "Decision",
            "Rationale",
            "Alternatives Considered",
            "Consequences",
        ]:
            self.assertIn(required, adr_readme)
            self.assertIn(required, tech_writer)

        self.assertIn("Optional ADR sections:", adr_readme)
        self.assertIn("Include when useful:", tech_writer)


if __name__ == "__main__":
    unittest.main()
